# Spring properties
spring:
  application:
     name: public-students  # Service registers under this name
  
#Component Info 
info:
  component: Public-RestService  
  
# HTTP Server
server:
  port: 0
   
#Service Registration Method 
cloud:
  services:
    registrationMethod: route
 
#Disable HTTP Basic Authentication
security:
  basic:
    enabled: false
    
# Discovery Server Access
eureka:
  client:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:{random.value}}}
 
